### ISSUE TITLE
Multiple same question variables

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#482] opened 2018-09-16 02:46 UTC
ex:

\<a--\>A\>. :|:
\<b--\>B\>. :|:
\<b--\>B\>. :|:

\<(&/, \<a--\>A\>, ?tx, ?z, ?ty) =/\> ?z\>?
'                   --           --

(wrong) Answer: <(&/,<a --> A>,+1010,<SELF --> [busy]>,+44983) =/> <b --> B>>. %1.00;0.03%

**Comment by patham9** [comment] 2018-11-24 01:19
The issue is actually caused by this:
https://github.com/opennars/opennars/commit/db35fb7ab19053c858211aedc35ac2174106e3d9#diff-07309571d8e26003041177a100a2f3ab
It was a bad decision to remove that. It only misses a potential containment check to make sure it can't lead to unbounded substitutions.
Hm another way would be checking whether the key is included already in the substitution map, and if yes, to compare the values. Hm.

**Comment by patham9** [comment] 2018-11-24 01:44
fixed with https://github.com/opennars/opennars/commit/8de0f0b347583ee3b310aaafef6a0a8212c48333

**Closed by patham9** 2018-11-24 01:44 UTC
Labels: bug
